### ISSUE TITLE
[Question] How can I download MolView image from my local machine?

### ISSUE THREAD

**Issue by AnubhabMondal** [molview/legacy-lite#1]
I clone this project and install [as per instruction] it. The Molview editor working fine in my local machine. But after my drawing, if I want to save the diagram in my local machine it gives an error.
![MolViewError](https://user-images.githubusercontent.com/43597328/89256572-106d3700-d642-11ea-9fb0-bce85924d7c3.png)

@bergwerf Can you please help me with this. Is there any way that I can download the Molview image.

**Comment by bergwerf** [comment]
It turns out there was an issue with the FileSaver.js version. I have fixed this. If you run `bower install` and `grunt` again you should get a working version. You can also extract the pre-compiled version in `dist`.

**Comment by AnubhabMondal** [comment]
Thank You ..!!!
